"use client";
// The blockDAG decoration, in two forms.
//
// DESKTOP (>= lg) — "rail": a narrow graph pinned in the left margin,
// outside the content column, moving at 1.35x scroll so it parallaxes and
// feels a little independent. Unchanged from what is deployed.
//
// MOBILE (< lg) — "backdrop": there is no left margin at that width, so the
// graph becomes a full-width layer BEHIND the hero and cards. Sitting under
// text forces three differences:
//
//   1. LOCKSTEP, NOT PARALLAX. Scroll factor is exactly 1.0 and the camera
//      is NOT eased — it snaps to scrollY. Easing here would be a bug you
//      can see: the graph would lag the cards by a few frames and read as
//      sliding underneath them. Locked means locked.
//   2. MUCH FAINTER. Intensity is 0.45 of the rail's — slightly under the
//      "about half" brief, on purpose, because the failure mode that
//      matters is body text becoming hard to read. If it still competes,
//      lower MOBILE_INTENSITY; legibility beats decoration every time.
//   3. BEHIND EVERYTHING, via a negative z-index, so no content can end up
//      underneath it.
//
// NEITHER FORM HAS SELF-MOTION. There is no timer anywhere: the camera is a
// function of scroll position alone, and blocks are generated by scroll
// DEPTH, not by a clock. A still page is a still graph, and scrolling down
// is what reveals more of the DAG.
//
// SIMULATED. No node is contacted — the page must look alive whether or not
// a node is reachable. Wiring real TN10 data later means replacing
// `spawnRound` alone.
//
// COST: one canvas per form, each with an rAF loop capped at ~30fps that
// SUSPENDS ITSELF once the camera settles and nothing is fading, so an idle
// page costs zero frames. Both stop when the tab is hidden or the layer is
// not displayed (each is display:none at the other's breakpoint, which the
// IntersectionObserver reports as not intersecting). Under
// prefers-reduced-motion neither starts a loop.
import { useEffect, useRef } from "react";

const ROW_H = 52;
const NODE = 6.5; // square — these are blocks
const NODE_R = 1.6;
const FRAME_MS = 1000 / 30;
const FADE_MS = 800;
const MAX_BLOCKS = 900;
const SETTLE_PX = 0.15;
const TEAL = "73, 234, 203";

/** Behind body text, so deliberately under half the rail's strength. */
const MOBILE_INTENSITY = 0.45;

interface Block {
  wy: number;
  dx: number; // px offset from the layer's horizontal centre
  born: number;
  parents: Block[];
}

interface Mode {
  /** >1 parallaxes; exactly 1 is lockstep with the page. */
  scrollFactor: number;
  /** Easing constant, or null to snap (required for true lockstep). */
  ease: number | null;
  laneW: number;
  intensity: number;
  /** Generate down to this fraction of the layer height. */
  genAhead: number;
  /** Rail rounds cluster on the centre; the backdrop scatters across the
   * full width. */
  spread: "centred" | "wide";
}

const RAIL: Mode = {
  scrollFactor: 1.35,
  ease: 220,
  laneW: 18,
  intensity: 1,
  genAhead: 0.78,
  spread: "centred",
};
const BACKDROP: Mode = {
  scrollFactor: 1,
  ease: null,
  laneW: 34,
  intensity: MOBILE_INTENSITY,
  genAhead: 0.9,
  spread: "wide",
};

function makeRand(seed: number) {
  let s = seed >>> 0;
  return () => {
    s = (s * 1664525 + 1013904223) >>> 0;
    return s / 4294967296;
  };
}

function useDagLayer(
  mode: Mode,
  seed: number,
  wrapRef: React.RefObject<HTMLDivElement | null>,
  canvasRef: React.RefObject<HTMLCanvasElement | null>
) {
  useEffect(() => {
    const wrap = wrapRef.current;
    const canvas = canvasRef.current;
    if (!wrap || !canvas) return;
    const ctx = canvas.getContext("2d");
    if (!ctx) return;

    const reduced = window.matchMedia("(prefers-reduced-motion: reduce)").matches;
    const rand = makeRand(seed);

    let blocks: Block[] = [];
    let frontier: Block[] = [];
    let deepestY = 0;
    let camera = 0;
    let cssW = 0;
    let cssH = 0;

    /** Uneven by design: mostly 2-5 with an occasional spike toward 7. A
     * flat uniform roll still reads as a metronome. */
    const roundSize = () => {
      let n = 2 + Math.floor(rand() * 4);
      if (rand() < 0.22) n += 1 + Math.floor(rand() * 2);
      return Math.min(7, n);
    };

    const spawnRound = (now: number) => {
      const count = roundSize();
      const round: Block[] = [];
      let offsets: number[];
      if (mode.spread === "centred") {
        // Anchored on the centre whatever the size, so a burst does not
        // shift the column sideways.
        offsets = Array.from(
          { length: count },
          (_, i) => (i - (count - 1) / 2) * mode.laneW
        );
      } else {
        // Scatter across the full width so it reads as a backdrop rather
        // than a column that happens to be centred.
        const laneCount = Math.max(3, Math.round(cssW / mode.laneW) - 1);
        const pool = Array.from({ length: laneCount }, (_, i) => i);
        const take = Math.min(count, laneCount);
        const chosen: number[] = [];
        for (let c = 0; c < take; c++) {
          chosen.push(pool.splice(Math.floor(rand() * pool.length), 1)[0]);
        }
        chosen.sort((a, b) => a - b);
        offsets = chosen.map((i) => (i - (laneCount - 1) / 2) * mode.laneW);
      }

      for (const dx of offsets) {
        const parents: Block[] = [];
        if (frontier.length) {
          const want = Math.min(frontier.length, 1 + Math.floor(rand() * 3));
          if (mode.spread === "wide") {
            // Nearest parents: across a wide band, random parents produce
            // long crossing edges that read as clutter behind text.
            const cand = [...frontier].sort(
              (p, q) => Math.abs(p.dx - dx) - Math.abs(q.dx - dx)
            );
            for (let p = 0; p < want; p++) parents.push(cand[p]);
          } else {
            const pool = [...frontier];
            for (let p = 0; p < want; p++) {
              parents.push(pool.splice(Math.floor(rand() * pool.length), 1)[0]);
            }
          }
        }
        round.push({ wy: deepestY, dx, born: now, parents });
      }
      blocks.push(...round);
      frontier = round;
      deepestY += ROW_H;
      if (blocks.length > MAX_BLOCKS) blocks = blocks.slice(-MAX_BLOCKS);
    };

    const measure = () => {
      const r = wrap.getBoundingClientRect();
      cssW = Math.max(1, r.width);
      cssH = Math.max(1, r.height);
      const dpr = Math.min(2, window.devicePixelRatio || 1);
      canvas.width = Math.round(cssW * dpr);
      canvas.height = Math.round(cssH * dpr);
      canvas.style.width = `${cssW}px`;
      canvas.style.height = `${cssH}px`;
      ctx.setTransform(dpr, 0, 0, dpr, 0, 0);
    };

    const fillTo = (targetWorldY: number, now: number) => {
      let guard = 0;
      while (deepestY < targetWorldY && guard++ < 400) spawnRound(now);
    };

    const cameraTarget = () => window.scrollY * mode.scrollFactor;

    const draw = (now: number) => {
      ctx.clearRect(0, 0, cssW, cssH);
      const cx = cssW / 2;
      const I = mode.intensity;
      const sx = (b: Block) => cx + b.dx;
      const sy = (b: Block) => b.wy - camera;
      const alphaOf = (b: Block) =>
        reduced ? 1 : Math.min(1, (now - b.born) / FADE_MS);

      ctx.lineWidth = 1;
      for (const b of blocks) {
        const y2 = sy(b);
        if (y2 < -ROW_H * 2 || y2 > cssH + ROW_H * 2) continue;
        const a = alphaOf(b);
        if (a <= 0) continue;
        const x2 = sx(b);
        for (const p of b.parents) {
          const x1 = sx(p);
          const y1 = sy(p);
          ctx.strokeStyle = `rgba(${TEAL}, ${0.15 * a * I})`;
          ctx.beginPath();
          ctx.moveTo(x1, y1);
          const my = (y1 + y2) / 2;
          ctx.bezierCurveTo(x1, my, x2, my, x2, y2);
          ctx.stroke();
        }
      }

      for (const b of blocks) {
        const y = sy(b);
        if (y < -ROW_H || y > cssH + ROW_H) continue;
        const a = alphaOf(b);
        if (a <= 0) continue;
        const x = sx(b);
        const age = now - b.born;
        if (!reduced && age < FADE_MS) {
          const g = 1 - age / FADE_MS;
          const s = NODE + 7 * g;
          ctx.beginPath();
          ctx.roundRect(x - s / 2, y - s / 2, s, s, NODE_R + 1.5);
          ctx.fillStyle = `rgba(${TEAL}, ${0.09 * g * I})`;
          ctx.fill();
        }
        ctx.beginPath();
        ctx.roundRect(x - NODE / 2, y - NODE / 2, NODE, NODE, NODE_R);
        ctx.fillStyle = `rgba(${TEAL}, ${0.5 * a * I})`;
        ctx.fill();
        ctx.strokeStyle = `rgba(${TEAL}, ${0.75 * a * I})`;
        ctx.stroke();
      }
    };

    measure();

    // ---- reduced motion: one static snapshot, no loop, no scroll ----
    if (reduced) {
      const render = () => {
        measure();
        blocks = [];
        frontier = [];
        deepestY = 0;
        camera = 0;
        fillTo(cssH * 2, 0);
        draw(FADE_MS);
      };
      render();
      const ro = new ResizeObserver(render);
      ro.observe(wrap);
      return () => ro.disconnect();
    }

    let raf = 0;
    let lastFrame = 0;
    let visible = true;
    let running = false;

    const anyFading = (now: number) =>
      blocks.length > 0 && now - blocks[blocks.length - 1].born < FADE_MS;

    const tick = (now: number) => {
      if (now - lastFrame < FRAME_MS) {
        raf = requestAnimationFrame(tick);
        return;
      }
      const dt = Math.min(80, now - lastFrame);
      lastFrame = now;

      const target = cameraTarget();
      if (mode.ease === null) {
        // LOCKSTEP: snap. Easing would visibly trail the content.
        camera = target;
      } else {
        camera += (target - camera) * Math.min(1, dt / mode.ease);
      }

      // Scroll-driven generation: scrolling down is what reveals more DAG.
      fillTo(camera + cssH * mode.genAhead, now);
      draw(now);

      if (Math.abs(target - camera) < SETTLE_PX && !anyFading(now)) {
        camera = target;
        draw(now);
        running = false;
        raf = 0;
        return; // suspend until the next scroll
      }
      raf = requestAnimationFrame(tick);
    };

    const wake = () => {
      if (running || !visible || document.hidden) return;
      running = true;
      lastFrame = performance.now() - FRAME_MS;
      raf = requestAnimationFrame(tick);
    };
    const stop = () => {
      running = false;
      if (raf) cancelAnimationFrame(raf);
      raf = 0;
    };

    // Seed so the layer is never empty, back-dating births so the initial
    // graph is settled rather than blooming all at once.
    const t0 = performance.now();
    let seeded = 0;
    camera = cameraTarget();
    while (deepestY < camera + cssH * mode.genAhead) {
      spawnRound(t0 - FADE_MS - seeded * 45);
      seeded++;
    }
    draw(t0);

    const onScroll = () => wake();
    window.addEventListener("scroll", onScroll, { passive: true });

    const io = new IntersectionObserver(
      (entries) => {
        visible = entries.some((e) => e.isIntersecting);
        if (visible) wake();
        else stop();
      },
      { threshold: 0 }
    );
    io.observe(wrap);
    const ro = new ResizeObserver(() => {
      measure();
      wake();
    });
    ro.observe(wrap);
    const onVisibility = () => (document.hidden ? stop() : wake());
    document.addEventListener("visibilitychange", onVisibility);

    return () => {
      stop();
      window.removeEventListener("scroll", onScroll);
      io.disconnect();
      ro.disconnect();
      document.removeEventListener("visibilitychange", onVisibility);
    };
  }, [mode, seed, wrapRef, canvasRef]);
}

const EDGE_MASK =
  "linear-gradient(to bottom, transparent 0%, black 14%, black 86%, transparent 100%)";

export function DagVisual() {
  const railWrap = useRef<HTMLDivElement | null>(null);
  const railCanvas = useRef<HTMLCanvasElement | null>(null);
  const backWrap = useRef<HTMLDivElement | null>(null);
  const backCanvas = useRef<HTMLCanvasElement | null>(null);

  useDagLayer(RAIL, 0xda6, railWrap, railCanvas);
  useDagLayer(BACKDROP, 0xba5e, backWrap, backCanvas);

  return (
    <>
      {/* DESKTOP: left-margin rail. `left` is derived from the same 42rem
          column the layout centres, so it tracks the content column at any
          width without ever overlapping it. */}
      <div
        ref={railWrap}
        aria-hidden
        style={{
          left: "calc((100vw - 42rem) / 2 - 9.75rem)",
          maskImage: EDGE_MASK,
          WebkitMaskImage: EDGE_MASK,
        }}
        className="hidden lg:block pointer-events-none select-none fixed top-0 z-0 h-screen w-[8.25rem]"
      >
        <canvas ref={railCanvas} className="block h-full w-full opacity-70" />
      </div>

      {/* MOBILE: full-width backdrop behind the content. Negative z-index
          keeps it under the page's text and cards regardless of render
          order. Note this element is display:none above lg and the rail is
          display:none below it, so only one layer is ever live — the other
          one's IntersectionObserver reports it hidden and suspends its
          loop. */}
      <div
        ref={backWrap}
        aria-hidden
        style={{
          zIndex: -1,
          maskImage: EDGE_MASK,
          WebkitMaskImage: EDGE_MASK,
        }}
        className="lg:hidden pointer-events-none select-none fixed inset-0"
      >
        <canvas ref={backCanvas} className="block h-full w-full opacity-70" />
      </div>
    </>
  );
}
