import { describe, it, expect } from "vitest";
import {
  encryptKasia1,
  encryptKasia1Internal,
  decryptKasia1,
  MIN_KASIA1_BYTES,
} from "../../src/lib/ask/crypto";
import { xOnlyFromAddress } from "../../src/lib/ask/covenant";
import { fromHex } from "../../src/lib/ask/protocol";
import { Keypair, PrivateKey } from "kaspa-wasm";

// COMPATIBILITY NOTE: Kasia's repo ships NO fixed cipher test vectors (only
// a randomized round-trip, cipher/src/lib.rs:346-363, verified 2026-08-03).
// These tests therefore prove (a) round-trip correctness against the SDK's
// real key/address types, (b) the structural properties Kasia's code relies
// on (even-parity lift, parity immunity, wire layout, legacy ephemeral),
// and (c) a pinned regression vector generated by THIS implementation.
// They cannot prove cross-implementation interop — that requires a blob
// from Kasia's own code and is flagged for the Kasia-team conversation.

describe("kasia1 cipher (crypto.ts)", () => {
  it("round-trips using only the recipient's ADDRESS to encrypt", () => {
    const kp = Keypair.random();
    const address = kp.toAddress("testnet-10").toString();
    const blob = encryptKasia1(xOnlyFromAddress(address), "hello, private world");
    expect(decryptKasia1(blob, kp.privateKey)).toBe("hello, private world");
  });

  it("has the kasia1 wire layout: nonce(12) | SEC1 ephemeral(33) | ct+tag", () => {
    const kp = Keypair.random();
    const blob = fromHex(encryptKasia1(xOnlyFromAddress(kp.toAddress("testnet-10").toString()), "x"));
    expect(blob.length).toBe(12 + 33 + 1 + 16); // 1-byte plaintext + tag
    expect([0x02, 0x03]).toContain(blob[12]); // SEC1 compressed prefix
    expect(blob.length).toBeGreaterThanOrEqual(MIN_KASIA1_BYTES);
  });

  it("decrypts regardless of the recipient key's actual parity (even-lift immunity)", () => {
    // Kasia lifts the address x-only key with assumed EVEN parity. For keys
    // whose real pubkey is odd, x-coordinate ECDH still agrees. Verify over
    // several random keys (both parities will occur).
    for (let i = 0; i < 8; i++) {
      const kp = Keypair.random();
      const blob = encryptKasia1(kp.xOnlyPublicKey.toString(), `msg ${i}`);
      expect(decryptKasia1(blob, kp.privateKey)).toBe(`msg ${i}`);
    }
  });

  it("accepts the legacy 32-byte x-only ephemeral key form on decrypt", () => {
    const kp = Keypair.random();
    const hex = encryptKasia1(xOnlyFromAddress(kp.toAddress("testnet-10").toString()), "legacy");
    const blob = fromHex(hex);
    if (blob[12] === 0x02) {
      // Drop the parity byte -> legacy layout; must still decrypt.
      const legacy = new Uint8Array(blob.length - 1);
      legacy.set(blob.subarray(0, 12), 0);
      legacy.set(blob.subarray(13), 12);
      const legacyHex = Array.from(legacy, (b) => b.toString(16).padStart(2, "0")).join("");
      expect(decryptKasia1(legacyHex, kp.privateKey)).toBe("legacy");
    } // odd ephemeral: legacy form can't represent it; nothing to assert
  });

  it("rejects tampered ciphertexts and wrong keys (Poly1305 integrity)", () => {
    const kp = Keypair.random();
    const blob = encryptKasia1(xOnlyFromAddress(kp.toAddress("testnet-10").toString()), "integrity");
    const tampered = blob.slice(0, blob.length - 2) + (blob.endsWith("00") ? "01" : "00");
    expect(() => decryptKasia1(tampered, kp.privateKey)).toThrow();
    const otherKey = Keypair.random().privateKey;
    expect(() => decryptKasia1(blob, otherKey)).toThrow();
  });

  it("matches the pinned known-answer vector (frozen 2026-08-03)", () => {
    // Deterministic KAT: recipient privkey = 1, ephemeral secret = 2, zero
    // nonce, plaintext "hi". Generated once by encryptKasia1Internal and
    // frozen — catches any KDF/cipher/layout drift. Independently checkable
    // structure: recipient x-only key = secp256k1 G.x; bytes 12..45 =
    // compressed 2*G (02c6047f...). NOT a Kasia cross-implementation vector
    // (none exist upstream — see header note).
    const recipientPriv =
      "0000000000000000000000000000000000000000000000000000000000000001";
    const VECTOR =
      "00000000000000000000000002c6047f9441ed7d6d3045406e95c07cd85c778e4b8cef3ca7abac09b95c709ee5acda3fde6ce7fc37fcb4f44c7aaed527b1ce";
    const kp = Keypair.fromPrivateKey(new PrivateKey(recipientPriv));
    expect(kp.xOnlyPublicKey.toString()).toBe(
      "79be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798" // G.x
    );
    const eph = new Uint8Array(32);
    eph[31] = 2;
    expect(
      encryptKasia1Internal(kp.xOnlyPublicKey.toString(), "hi", eph, new Uint8Array(12))
    ).toBe(VECTOR);
    expect(decryptKasia1(VECTOR, recipientPriv)).toBe("hi");
  });
});
